version: '3.8'

services:
  setudb:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: Kaustubh1
      MYSQL_DATABASE: setudb
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3

  setubackend:
    image: kaustubhdeokar/setubackend
    depends_on:
      - setudb
    environment:
      MYSQL_HOST: setudb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Kaustubh1
      MYSQL_PASSWORD: Kaustubh1
      MYSQL_DB: setudb
      MYSQL_PORT: 3306
    ports:
      - "8000:8000"
    networks:
      - app-network

  setufrontend:
    image: kaustubhdeokar/setufrontend
    depends_on:
      - setubackend
    ports:
      - "4173:4173"
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - setubackend
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    command: "http setubackend:8000"
    ports:
      - "4040:4040"  # Ngrok web interface
    networks:
      - app-network

networks:
  app-network:
    driver: bridge